### ISSUE TITLE
[FIX] export 방식 통일

### ISSUE THREAD

**Issue by Kong-E** [Dingdongrami/PicMap_frontend#20]
### 페이지
- [x] 페이지 컴포넌트는 default로 export 하기
- [x] 각 페이지 디렉토리 index.js에서 `default as 컴포넌트 이름`으로 export 하기
- [x] screens의 index.js에서 export 하기

### 참고자료
(ex) 구현화면 및 궁금한 사항, 참고자료 등을 작성해주세요.

**Comment by g2Min** [comment]
넹
